include $(TOPDIR)/rules.mk

LUCI_TITLE:=W1700K SoftEther VPN server controls
LUCI_DEPENDS:=+luci-base +softethervpn5-server
LUCI_PKGARCH:=all
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
