include $(TOPDIR)/rules.mk

LUCI_TITLE:=Read-only W1700K NPU status
LUCI_DEPENDS:=+luci-base +w1700k-npu-status
LUCI_PKGARCH:=all
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
